# Generated by Django 4.2.5 on 2023-09-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(to="blog.category", verbose_name="دسته بندی"),
        ),
    ]
