# Generated by Django 4.2.5 on 2023-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_ipaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hits",
            field=models.ManyToManyField(
                blank=True,
                related_name="hits",
                to="blog.ipaddress",
                verbose_name="بازدید ها",
            ),
        ),
    ]
