# Generated by Django 4.2.5 on 2023-10-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_article_hits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="hits",
        ),
    ]
