# Generated by Django 4.2.5 on 2023-10-31 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_articlehit_article_hits"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlehit",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
